apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server-panel.fullname" . }}
  labels:
    {{- include "server-panel.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "server-panel.databaseUrl" . | quote }}
  secret-key: {{ .Values.config.secretKey | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
